import json
import math
import re
from itertools import product
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent
RESULT_FILE = ROOT / "simulation_results.json"
OUTPUT_FILE = ROOT / "docs" / "odds-data.js"
SCENARIO_RE = re.compile(r"^[SML](D2|DD)J{0,2}$")
WAGER_TYPES = (("Trifecta", 3), ("Exacta", 2), ("Win", 1))


def parse_scenario(scenario: str) -> tuple[int, int]:
    match = SCENARIO_RE.fullmatch(scenario)
    if match is None:
        raise ValueError(f"Unsupported scenario name: {scenario!r}")
    if match.group(1) == "D2":
        return 1, 3
    return 2, 2


def falling_factorial(size: int, selected: int) -> int:
    result = 1
    for value in range(size, size - selected, -1):
        result *= value
    return result


def equivalent_ticket_count(selection: str, d_suits: int, other_suits: int) -> int:
    d_count = selection.count("D")
    other_count = selection.count("@")
    if d_count > d_suits or other_count > other_suits:
        return 0
    return falling_factorial(d_suits, d_count) * falling_factorial(
        other_suits, other_count
    )


def validate_counts(
    scenario: str, counts: Any, d_suits: int, other_suits: int
) -> dict[str, int]:
    if not isinstance(counts, dict) or not counts:
        raise ValueError(f"Scenario {scenario!r} must contain result counts")

    validated: dict[str, int] = {}
    for result, count in counts.items():
        if not isinstance(result, str) or len(result) != 3 or set(result) - {"D", "@"}:
            raise ValueError(f"Invalid result {result!r} in scenario {scenario!r}")
        if result.count("D") > d_suits or result.count("@") > other_suits:
            raise ValueError(f"Impossible result {result!r} in scenario {scenario!r}")
        if isinstance(count, bool) or not isinstance(count, int) or count < 0:
            raise ValueError(
                f"Count for {scenario!r}/{result!r} must be a nonnegative integer"
            )
        validated[result] = count

    if sum(validated.values()) == 0:
        raise ValueError(f"Scenario {scenario!r} has no valid trials")
    return validated


def calculate_scenario(scenario: str, raw_counts: Any) -> list[dict[str, Any]]:
    d_suits, other_suits = parse_scenario(scenario)
    counts = validate_counts(scenario, raw_counts, d_suits, other_suits)
    valid_trials = sum(counts.values())
    rows: list[dict[str, Any]] = []

    for wager_type, places in WAGER_TYPES:
        wager_rows: list[dict[str, Any]] = []
        for symbols in product(("D", "@"), repeat=places):
            selection = "".join(symbols)
            equivalents = equivalent_ticket_count(selection, d_suits, other_suits)
            if equivalents == 0:
                continue

            grouped_count = sum(
                count
                for result, count in counts.items()
                if result.startswith(selection)
            )
            if grouped_count == 0:
                raise ValueError(
                    f"Scenario {scenario!r} has no wins for possible selection {selection!r}"
                )

            probability = grouped_count / valid_trials / equivalents
            decimal_odds = 1 / probability
            if not math.isfinite(decimal_odds) or decimal_odds <= 0:
                raise ValueError(f"Invalid odds for {scenario!r}/{selection!r}")

            wager_rows.append(
                {
                    "wagerType": wager_type,
                    "selection": selection,
                    "equivalentTickets": equivalents,
                    "probabilityPercent": probability * 100,
                    "decimalOdds": decimal_odds,
                }
            )
        wager_rows.sort(key=lambda row: row["decimalOdds"], reverse=True)
        rows.extend(wager_rows)
    return rows


def calculate_all(raw_results: Any) -> dict[str, list[dict[str, Any]]]:
    return {
        scenario: calculate_scenario(scenario, counts)
        for scenario, counts in raw_results.items()
    }


def render_javascript(odds_data: dict[str, list[dict[str, Any]]]) -> str:
    serialized = json.dumps(odds_data, indent=2, ensure_ascii=False, allow_nan=False)
    return (
        "/* Generated by calculate_odds.py. Do not edit manually. */\n"
        f"const ODDS_DATA = Object.freeze({serialized});\n"
    )


def main() -> None:
    raw_results = json.loads(RESULT_FILE.read_text(encoding="utf-8"))
    odds_data = calculate_all(raw_results)
    OUTPUT_FILE.write_text(render_javascript(odds_data), encoding="utf-8")
    print(f"Saved odds for {len(odds_data)} scenarios to {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
